.TH UTILITIES 1 "12-03-2024" "1.0" "User Commands"
.SH NAME
UTILITIES \- generate UUIDs
.SH SYNOPSIS
.B UTILITIES
.RB [ -v1 | -v4 ]
.SH DESCRIPTION
.PP
This script generates Universally Unique Identifiers (UUIDs).
.SH OPTIONS
.TP
.BI "-v1, --version1"
Generate UUID version 1 (time-based).
.TP
.BI "-v4, --version4"
Generate UUID version 4 (random).
.SH AUTHOR
Alex Ward (AW94)
.SH SEE ALSO
.BR uuidgen (1)
